// Layout Templates
export const LAYOUT_TEMPLATES = {
    preset1: {
        flexDirection: "column",
    },
    preset2: {
        flexDirection: "row",
    },
    preset3: {
        flexDirection: "row",
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset4: {
        flexDirection: "row",
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 30,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 70,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset5: {
        flexDirection: "row",
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset6: {
        flexDirection: "row",
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 25,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset7: {
        flexDirection: "row",
        flexWrap: "wrap",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset8: {
        flexDirection: "row",
        flexWrap: "wrap",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 100,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset9: {
        flexDirection: "row",
        alignItems: "stretch",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 50,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container",
                {
                    containerLayout: "preset1",
                    flexDirection: "column",
                    isContainerCustomWidth: true,
                    containerCustomWidthRange: 50,
                    MOBcontainerCustomWidthRange: 100,
                    MOBcontainerCustomWidthUnit: "%",
                    containerWidth: "custom",
                    flexColumnGapRange: 0,
                    flexRowGapRange: 0,
                }, [
                    ["essential-blocks/flex-container", {
                        containerLayout: "preset1",
                        flexDirection: "column",
                        isContainerCustomWidth: true,
                        containerCustomWidthRange: 100,
                        MOBcontainerCustomWidthRange: 100,
                        MOBcontainerCustomWidthUnit: "%",
                        containerWidth: "custom",
                    }],
                    ["essential-blocks/flex-container", {
                        containerLayout: "preset1",
                        flexDirection: "column",
                        isContainerCustomWidth: true,
                        containerCustomWidthRange: 100,
                        MOBcontainerCustomWidthRange: 100,
                        MOBcontainerCustomWidthUnit: "%",
                        containerWidth: "custom",
                    }],
                ]],
        ]
    },
    preset10: {
        flexDirection: "row",
        flexWrap: "wrap",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset11: {
        flexDirection: "row",
        flexWrap: "wrap",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 33.3333,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 66.6666,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
    preset12: {
        flexDirection: "row",
        flexWrap: "wrap",
        flexColumnGapRange: 0,
        flexRowGapRange: 0,
        blocks: [
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 70,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 30,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 30,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
            ["essential-blocks/flex-container", {
                containerLayout: "preset1",
                flexDirection: "column",
                isContainerCustomWidth: true,
                containerCustomWidthRange: 70,
                MOBcontainerCustomWidthRange: 100,
                MOBcontainerCustomWidthUnit: "%",
                containerWidth: "custom",
            }],
        ]
    },
};

