const IconList = [
	"fab fa-facebook",
	"fab fa-facebook-f",
	"fab fa-twitter",
	"fab fa-twitter-square",
	"fab fa-linkedin",
	"fab fa-linkedin-in",
	"fab fa-pinterest",
	"fab fa-reddit",
	"fab fa-whatsapp",
	"fab fa-tumblr",
	"fab fa-telegram",
	"fab fa-get-pocket",
	"fas fa-envelope",
	"far fa-envelope",
	"fab fa-xing-square",
	"fab fa-xing",
	"fab fa-vk",
];
export default IconList;
