<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.6.0
 *
 * @package uagb
 */

return array(
	'separatorAlign'                 => 'center',
	'separatorAlignTablet'           => 'center',
	'separatorAlignMobile'           => 'center',
	'separatorStyle'                 => 'solid',
	'separatorBorderHeight'          => 3,
	'separatorBorderHeightMobile'    => '',
	'separatorBorderHeightTablet'    => '',
	'separatorBorderHeightUnit'      => 'px',
	'separatorWidth'                 => 100,
	'separatorWidthTablet'           => 100,
	'separatorWidthMobile'           => 100,
	'separatorWidthType'             => '%',
	'separatorSize'                  => 5,
	'separatorSizeTablet'            => 5,
	'separatorSizeMobile'            => 5,
	'separatorSizeType'              => 'px',
	'separatorHeight'                => '',
	'separatorHeightMobile'          => '',
	'separatorHeightTablet'          => '',
	'separatorHeightType'            => 'px',
	'separatorColor'                 => '',
	'elementType'                    => 'none',
	'elementPosition'                => 'center',
	'elementSpacing'                 => 15,
	'elementSpacingTablet'           => 15,
	'elementSpacingMobile'           => 15,
	'elementSpacingUnit'             => 'px',
	'elementTextLoadGoogleFonts'     => false,
	'elementTextFontFamily'          => 'Default',
	'elementTextFontWeight'          => '',
	'elementTextFontSize'            => '',
	'elementTextFontSizeType'        => 'px',
	'elementTextFontSizeTablet'      => '',
	'elementTextFontSizeMobile'      => '',
	'elementTextLineHeightType'      => 'em',
	'elementTextLineHeight'          => 1,
	'elementTextLineHeightTablet'    => 1,
	'elementTextLineHeightMobile'    => 1,
	'elementTextFontStyle'           => 'normal',
	'elementTextLetterSpacing'       => '',
	'elementTextLetterSpacingTablet' => '',
	'elementTextLetterSpacingMobile' => '',
	'elementTextLetterSpacingType'   => 'px',
	'elementTextDecoration'          => '',
	'elementTextTransform'           => '',
	'elementColor'                   => '',
	'elementIconWidth'               => '',
	'elementIconWidthTablet'         => '',
	'elementIconWidthMobile'         => '',
	'elementIconWidthType'           => 'px',
	// padding.
	'blockTopPadding'                => '',
	'blockRightPadding'              => '',
	'blockLeftPadding'               => '',
	'blockBottomPadding'             => '',
	'blockTopPaddingTablet'          => '',
	'blockRightPaddingTablet'        => '',
	'blockLeftPaddingTablet'         => '',
	'blockBottomPaddingTablet'       => '',
	'blockTopPaddingMobile'          => '',
	'blockRightPaddingMobile'        => '',
	'blockLeftPaddingMobile'         => '',
	'blockBottomPaddingMobile'       => '',
	'blockPaddingUnit'               => '',
	'blockPaddingUnitTablet'         => '',
	'blockPaddingUnitMobile'         => '',
	'blockPaddingLink'               => '',
	// margin.
	'blockTopMargin'                 => '',
	'blockRightMargin'               => '',
	'blockLeftMargin'                => '',
	'blockBottomMargin'              => '',
	'blockTopMarginTablet'           => '',
	'blockRightMarginTablet'         => '',
	'blockLeftMarginTablet'          => '',
	'blockBottomMarginTablet'        => '',
	'blockTopMarginMobile'           => '',
	'blockRightMarginMobile'         => '',
	'blockLeftMarginMobile'          => '',
	'blockBottomMarginMobile'        => '',
	'blockMarginUnit'                => 'px',
	'blockMarginUnitTablet'          => 'px',
	'blockMarginUnitMobile'          => 'px',
	'blockMarginLink'                => '',
);
